name: png_file_checks

# Check whether all png files are in a valid format
on:
  workflow_dispatch:

jobs:
  png_optimized:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt install -y optipng

      - name: Check whether all png files are optimized
        run: |
          ./util/ci/check_png_optimized.sh
